### ISSUE TITLE
Extract uhdm frontend to independent yosys plugin

### ISSUE THREAD

**Issue by pawelsag** [antmicro/yosys#442]
Extracting the [uhdm-plugin](https://github.com/antmicro/yosys-symbiflow-plugins/tree/uhdm-plugin/uhdm-plugin) from yosys frontend allows us to make the uhdm processing independent from yosys version.
With such ability, software like edalize(or potentially other software..) can use the uhdm plugin regardless of the yosys version.

Current status:
- [X]  Extract the uhdm frontend to separate plugin
- [X]  Rebase the uhdm-yosys branch to upstream version
- [X]  Integrate uhdm-plugin with yosys
- [x] Solve the problems with yosys after rebase (look at known issues section)
- [x] Build the ibex with working bitstream
- [x] Build the opentitan with working bitstream
- [x] Fix the CI tests after rebase
- [x] Update uhdm-yosys conda package to use uhdm-plugin. The [link](https://github.com/hdl/conda-eda/pull/118) for PR.
- [x] Change the fpga-tool-perf and sv-tests to use updated packages
  - [x] sv-tests PR: https://github.com/chipsalliance/sv-tests/pull/1702
  - [x] fpga-tool-perf PR: https://github.com/SymbiFlow/fpga-tool-perf/pull/340
- [x] Update UHDM-integration-tests to use uhdm-plugin: https://github.com/chipsalliance/UHDM-integration-tests/pull/355

## Known issues
 - [x] The SIGSEGV exception is being thrown when we try to run the yosys on this [sv file](https://github.com/antmicro/yosys/blob/39d32c2cece005c6bd33e86b96ba5ad1d5728819/uhdm-tests/opentitan/custom_files/padring.v)

**Comment by kamilrakoczy** [comment]
Everything from the list is done, we should use uhdm as a plugin everywhere now. Closing this issue.
